version: '3.7'

# Set up all services
services:

  postgres-service:
    image: postgres:16.1
    restart: always
    container_name: postgres-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "1"
    ports:
      - 5532:5432

  application.service:
    restart: always
    container_name: application.service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8088
      - ASPNETCORE_HTTPS_PORTS=8089
    ports:
      - 8088:8088
    build:
      context: ../
      dockerfile: Docker/DockerfileCompose
    depends_on:
      - postgres-service

volumes:
  postgres_data:
